apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kafka-ui
  namespace: kafka
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/hostname: kafka.loenskov.com
    traefik.ingress.kubernetes.io/router.middlewares: kafka-kafka-ui-basic-auth@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - kafka.loenskov.com
    secretName: kafka-ui-tls
  rules:
  - host: kafka.loenskov.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kafka-ui
            port:
              number: 80
